### ISSUE TITLE
[Symfony] Upgrade for Symfony 6

### ISSUE THREAD

**Issue by chadyred** [goodwix/doctrine-json-odm#19]
See #18

**Comment by strider2038** [comment]
Hello, @chadyred! I've updated dependencies in the master branch. Can you test it in your project?

**Comment by chadyred** [comment]
Great, thanks, could you provide a tag `0.6.0` and you will be the best :D

**Comment by strider2038** [comment]
Release https://github.com/goodwix/doctrine-json-odm/releases/tag/v0.6.0

**Comment by chadyred** [comment]
Thanks, from France :D
