### ISSUE TITLE
[FAQ] Is their a way to handle "abstract" by storing the type of concret class ?

### ISSUE THREAD

**Issue by chadyred** [goodwix/doctrine-json-odm#20]
Hello,

Thanks for your works.

I search a way to type with an abstract, but at deserialization time, it doesn't know the concrete "real" type of the stored object. So it says to me "Impossible to create instance of an abstract", logic, as it is an abstract :D

Is their a way to distinct the real type between each children instance at serialization ?

Maybe this way : [Symfony serializer : discriminator](https://symfony.com/doc/current/components/serializer.html#serializing-interfaces-and-abstract-classes)

I will make a try and do a test with that, or document that.... 

See you :)

**Comment by chadyred** [comment]
Hello,

Si I try with the link above, and It works :

```php
<?php

declare(strict_types=1);

namespace App\Whatever;

use Symfony\Component\Serializer\Annotation\DiscriminatorMap;

#### PHP8 Attribute####
#[DiscriminatorMap(
    typeProperty: 'type',
    mapping: [
        'myChildTypeName' => 'App\Whatever\Child',
        'myChild2TypeName' => 'App\Whatever\Child2',
    ]
)]


#### PHP < PHP8 ####
/**
 * @DiscriminatorMap(typeProperty="type", mapping={
 *    "myChildTypeName"="App\Whatever\Child",
 *    "myChild2TypeName"="App\Whatever\Child2"
 * })
 */


abstract class MyAbstract
{
}

class Child extends MyAbstract
{}


class Child2 extends MyAbstract
{}
```

ODM or not, I think it could be great to add an example in documentation about the fact the ODM Type handle this case too, isn't it ?

**Comment by strider2038** [comment]
Hello, @chadyred ! Thank you for the example. Can you add this to `README.md` in a pull request?

**Comment by chadyred** [comment]
Done
